services:
  - type: worker
    name: stock-ctr-python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true

    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: GUILD_ID
        sync: false

    disk:
      name: stock-data
      mountPath: /var/data
      sizeGB: 1
